### ISSUE TITLE
I would like to ask the default location

### ISSUE THREAD

**Issue by hungwei0331** [comyarzaheri/Sol#30]
Pardon me, I would like to ask the default location

because I saw those content in mainViewcontroller,

self.locationManager = [[CLLocationManager alloc]init];
        self.locationManager.desiredAccuracy = kCLLocationAccuracyThreeKilometers;
        self.locationManager.distanceFilter = 3000;
        self.locationManager.delegate = self;
        [self.locationManager startUpdatingLocation];

but after turn on the app it cant change the user's location,

how could I fix it? thank you for reply in advance.

**Comment by comyarzaheri** [comment]
There's no default location in the app, it uses the device's location. You can also search for a specific location by tapping the `+` button. I'll resolve this, but feel free to open the issue again if you have any more questions.
